### PR TITLE
Updated LiquidFun build scripts for Android

### PR DESCRIPTION
**Pull request by znakeeye**
This prepares for upcoming PR for integration of AGDK GameActivity.

Previously, the prebuilt `LiquidFun` library targeted `GNU STL` (deprecated in Android) which caused linking errors when linking with `libstdc++_shared`. Modern Android apps should only use the latter.

### CODE REVIEW

**Comment by iarwain** [comment]
Thanks, could you also add the new binaries themselves in /lib/android/... ?

**Comment by znakeeye** [comment]
> Thanks, could you also add the new binaries themselves in /lib/android/... ?

Issued `ndk-build` command, and copied the resulting `.a` files to the `lib` folder. Though, I advise consumers to re-compile these libraries to avoid any NDK/C++ compatibility issues.

The Android integration (e.g. the demo app) itself will not use these precompiled libraries.

**Comment by iarwain** [comment]
What about building orx itself, without the demo, will this also rebuild liquidfun?
If so we can remove the android lib folder for it entirely.

**Comment by znakeeye** [comment]
Yes. There will soon be a PR which describes all the steps in detail.

It will look something like this:

```sh
# Step 1: Build and install orx. All dependencies will be built too.
cd code/build/android
./gradlew build publishToMavenLocal
# Step 2: Build the demo (requires orx)
cd code/demo/android
./gradlew assemble
```

**Comment by iarwain** [comment]
In that case we can get rid of all pre-built binaries for Android, this will also have the advantage to make the `extern` archive downloaded by the `setup` script smaller.

**Pull request merged**
